Added logic to check for mother superior vs. sisters and dedicated vs. shared.

diff --git a/torque/epilogue b/torque/epilogue
--- a/torque/epilogue
+++ b/torque/epilogue
@@ -1,149 +1,127 @@
-#!/bin/ksh
+#!/bin/bash
+#
+# Gordon epilogue, called on the mom. Calls the common script,
+# epilogue.common.
+#
+# See the Torque docs for reference:
+# http://docs.adaptivecomputing.com/torque/Content/topics/12-appendices/prologueAndEpliogueScripts.htm
+
 PBS_JOBID=$1
 PBS_USER=$2
-GROUP=$3
-JOB=$4
-SESSION=$5
-LIMITS=$6
-RES=$7
-QUEUE=$8
-ACCOUNT=$9
+PBS_GROUP=$3
+PBS_JOBNAME=$4
+PBS_SESSION_ID=$5
+PBS_RESOURCE_LIMITS=$6
+PBS_RESOURCES_USED=$7
+JOB_QUEUE=$8
+JOB_ACCT=$9
+JOB_EXIT_CODE=$10
 
-function remove_file
-{
-        if [ -z "$(/sbin/fuser $1 2>/dev/null)" ]; then
-           /bin/rm -f $1
-        fi
+TORQUE_HOME=/var/spool/torque
+
+this_host=$(/bin/hostname -s)
+
+function check_status(){
+    # $1 = expected value
+    # $2 = status
+    # $3 = message if different
+    # Offline node if any checks fail and exit
+
+    if [[ $1 != $2 ]] ; then
+        note=$3
+        /opt/torque/bin/pbsnodes -oN "$note" $this_host
+        /usr/bin/logger -p local0.alert "Node offlined due to: $note"
+        exit -1
+    fi
 }
 
+function user_cleanup(){
+    # Called at end of last job by user to:
+    #  * killall PIDs
+    #  * semaphores
+    #  * shm
+    #  * remove /tmp files
 
-/usr/bin/logger -p local0.alert "********  running epilogue at $(date) for job PBS_JOBID $1"
+    /usr/bin/killall -9 -u $PBS_USER 
 
-#Remove user from access.conf
-/usr/bin/perl -pi -e "s/\s*$PBS_USER\b//" /etc/security/access.conf
+    # kill leftover allocated semiphores
+    for S in $(/usr/bin/ipcs -s | /bin/grep "$PBS_USER" | awk '{print $2}') ; do
+        /usr/bin/ipcrm -s $S 
+    done
 
-PBS_HOME=/var/spool/torque
+    # kill leftover allocated shared memory
+    for M in $(ipcs -m | grep "$PBS_USER" | grep -v key | awk '{print $2}') ; do
+        /usr/bin/ipcrm -m $M
+    done
 
-
-# Kill leftover from user not associated with PBS_JOBID : 
-   # as user delete the temporary directory
-   su - $PBS_USER -c "/bin/rm -rf /tmp/PBS_TEMP_$PBS_JOBID "
-
-   # see if there are other temporary directories on this node
-   # which are owned by the same user
-   others=$(su - $PBS_USER -c "ls -ld /tmp/PBS_TEMP_* "  2> /dev/null | awk -F" " ' { print $3, $NF }' | grep $PBS_USER |  awk -F" " ' { print $NF }')
-   # Only kill leftovers if that user doesn't have any other jobs on that node
-   if [ "$others" == "" ]; then
-
-      logger -p local0.alert "$HN KILLING leftover PID from PBS_JOBID $PBS_JOBID"
-      /usr/bin/killall -9 -u $PBS_USER 
-      sleep 10
-      /usr/bin/killall -9 -u $PBS_USER
-
-     # kill leftover allocated semiphores
-      if [ -n $(ipcs -s | grep " $PBS_USER ") ]; then
-      for S in $(ipcs -s | grep " $PBS_USER " | awk ' {print $2} '); do
-      /usr/bin/ipcrm -s $S 
-      done
-      fi
-
-     # kill leftover allocated shared memory
-      if [ -n $(ipcs -m | grep " $PBS_USER ") ]; then   
-      for M in $(ipcs -m | grep " $PBS_USER " | grep -v key| awk ' {print $2} '); do
-      /usr/bin/ipcrm -m $M
-      done
-      fi
-
-     # Left Over processes that do not kill
-     LO=$(/bin/ps -u $PBS_USER -o "pid=")
-     # wait a little while and check again
-     if [ -n "$LO" ] ; then
-       /bin/sleep 20
-     fi
-
-     LO=$(/bin/ps -u $PBS_USER -o "pid=")
-     if [ -n "$LO" ] ; then
-       for i in $LO ; do
-        /usr/bin/logger -p local0.alert "*******  $HN leftover PID $i from PBS_JOBID $PBS_JOBID"
-       done
-    # /opt/torque/bin/pbsnodes -o $(/bin/hostname -s)
-      /opt/torque/bin/pbsnodes -o -N "leftover PID from $PBS_JOBID" $(/bin/hostname -s)
-     fi
-   
-    # kill any files the user created in /tmp
-    tmpfiles=`/bin/ls -l /tmp | /bin/awk ' {print $3 " " $9}' | /bin/grep "^$PBS_USER" | /bin/awk ' {print $2}'`
-    if test -n "$tmpfiles"; then
-      for F in $tmpfiles; do
-       /bin/rm -fr /tmp/$F
-      done
+    # Left Over processes that do not kill
+    LO=$(/bin/ps -u $PBS_USER -o "pid=")
+    # wait a little while and check again
+    if [[ -n "$LO" ]] ; then
+        /bin/sleep 10
     fi
 
-   else
-     logger -p local0.alert "$HN other jobs running $PBS_JOBID and $others"
-   fi
-
-
-
-# Remove Oasis per job scratch space if it is empty
-/usr/sbin/lctl --net tcp ping 172.25.32.125  > /dev/null 2>&1
-R1=$?
-/usr/sbin/lctl --net tcp ping 172.25.32.253  > /dev/null 2>&1
-R2=$?
-
-if [[ $R1 == 0 || $R2 == 0 ]] ; then
-    if [ -d /oasis/scratch/$PBS_USER/$PBS_JOBID ] ; then
-	/bin/rmdir  --ignore-fail-on-non-empty /oasis/scratch/$PBS_USER/$PBS_JOBID
-	/usr/bin/logger -p local0.alert "epilogue: remove if empty /oasis/scratch/$PBS_USER/$PBS_JOBID"
-    else
-	/usr/bin/logger -p local0.alert "epilogue: /oasis/scratch/$PBS_USER/$PBS_JOBID does not exist "
+    LO=$(/bin/ps -u $PBS_USER -o "pid=")
+    if [[ -n "$LO" ]] ; then
+        for i in $LO ; do
+            /usr/bin/logger -p local0.alert "Leftover PID $i from PBS_JOBID $PBS_JOBID"
+        done
+        # Force node offline
+        check_status 0 1 "Leftover process from $PBS_JOBID"
     fi
+
+    # Remove any files the user created in /tmp
+    # Don't remcurse to remove directories, only remove files
+    /bin/find /tmp -user $USER -type 'f' -print0 | /usr/bin/xargs -0 -r rm -f  
+}
+
+# Check for whether node is dedicated or shared
+
+if [[ $JOB_QUEUE == "normal" ]] ; then
+    # Dedicate use, clean up all job lock files
+    /bin/rm -f /tmp/PBS_TEMP_*
+
+    # Make sure access.conf is clean
+    /bin/echo '-:ALL EXCEPT root (wheel) (xsede-admin):ALL' > /etc/security/access.conf
+    user_cleanup
 else
-    /usr/bin/logger -p local0.alert  "epilogue: /oasis not responding!!!"
-    /opt/torque/bin/pbsnodes -o $(hostname -s)
-    /opt/torque/bin/pbsnodes -N "/oasis not responding" $(hostname -s)
+    # Shared use, only remove up this job's lock file
+    /bin/su - $PBS_USER -c "/bin/rm -f /tmp/PBS_TEMP_$PBS_JOBID "    
+
+    # Remove user from access.conf
+    # N.B. This only removes the first entry
+    /bin/sed -i "s/$PBS_USER//" access.conf 
+
+    # Check for other jobs before cleaning up user activity
+    other_jobs=$(/bin/find /tmp -maxdepth 1  -name 'PBS_TEMP_*' -user $PBS_USER)
+    if [[ -z "$other_jobs" ]] ; then
+        user_cleanup
+    else
+        # Kill process group of job
+        /bin/kill -9 -$PBS_SESSION_ID
+    fi
 fi
+
+# Record current /scratch usage
+block_usage=$(/bin/df -B 1024 /scratch | /bin/grep scratch)
+inode_usage=$(/bin/df -i /scratch | /bin/grep scratch)
+/usr/bin/logger -p local0.alert "sdsc_stats job end $PBS_JOBID $PBS_USER local scratch block usage $block_usage"
+/usr/bin/logger -p local0.alert "sdsc_stats job end $PBS_JOBID $PBS_USER local scratch inode usage $inode_usage"
 
 # Remove local per job scratch space
-if [ -d /scratch/$PBS_USER/$PBS_JOBID ] ; then
-    # Record current /scratch usage
-    block_usage=$(/bin/df -B 1024 /scratch | grep scratch)
-    inode_usage=$(/bin/df -i /scratch | grep scratch)
-    /usr/bin/logger -p local0.alert "sdsc_stats job end $PBS_JOBID $PBS_USER local scratch block usage $block_usage"
-    /usr/bin/logger -p local0.alert "sdsc_stats job end $PBS_JOBID $PBS_USER local scratch inode usage $inode_usage"
+/bin/rm -rf /scratch/$PBS_USER/$PBS_JOBID
+check_status 0 $? "Cannot remove local scratch space"
 
-    /bin/rm -rf /scratch/$PBS_USER/$PBS_JOBID
-    /usr/bin/logger -p local0.alert "epilogue: removed /scratch/$PBS_USER/$PBS_JOBID"
-else
-    /usr/bin/logger -p local0.alert "epilogue: /scratch filesystem not mounted"
+# Mother superior removes Oasis scratch dir if empty
+if [[ -e /var/spool/torque/aux/$PBS_JOBID ]] ; then
+    /bin/rmdir --ignore-fail-on-non-empty /oasis/scratch/$PBS_USER/$PBS_JOBID
+    check_status 0 $? "Lustre issue, cannot remove Oasis scratch dir for $PBS_JOBID"
 fi
 
-
-# get rid of all ordinary files in the /tmp directory older than 168h (7 days)
+# Clean up /tmp
+# Get rid of all ordinary files in the /tmp directory older than 168h (7 days)
 # and not accessed or modified in the past 168 hours.
 
-/usr/bin/find /tmp -xdev -atime +8 -mtime +8 -type f -print | \
-        while read FILE2REM
-        do
-                remove_file $FILE2REM
-        done
+/usr/bin/find /tmp -xdev -atime +8 -mtime +8 -type 'f' -print0 | /usr/bin/xargs -0 -r rm -f
 
-
-# check for auotmount 
-/bin/ps -ef |grep automount |grep -v grep > /dev/null 2>&1
-st=$?
-if [ $st -ne 0 ] ; then
-    /sbin/service autofs start >> /var/log/local0 2>&1
-    sleep 10
-    /bin/ps -ef |grep automount |grep -v grep > /dev/null 2>&1
-    st=$?
-    if [ $st -ne 0 ] ; then
-        /usr/bin/logger -p local0.alert  "epilogue: automount not started, Giving up!  exit=2 "
-        /opt/torque/bin/pbsnodes -o $(hostname -s)
-        /opt/torque/bin/pbsnodes -N "automount failed" $(hostname -s)
-	exit 2
-    fi
-fi
-   
 exit 0
-
-
diff --git a/torque/prologue b/torque/prologue
--- a/torque/prologue
+++ b/torque/prologue
@@ -1,117 +1,65 @@
-#!/bin/ksh
+#!/bin/bash
+#
+# Gordon prologue, called on the mom. Calls the common script,
+# prologue.common.
+#
+# See the Torque docs for reference:
+# http://docs.adaptivecomputing.com/torque/Content/topics/12-appendices/prologueAndEpliogueScripts.htm
+
 PBS_JOBID=$1
 PBS_USER=$2
-GROUP=$3
+PBS_GROUP=$3
+PBS_JOBNAME=$4
+PBS_RESOURCE_LIMITS=$5
+JOB_QUEUE=$6
+JOB_ACCT=$7
 
-HOSTNAME=$(/bin/hostname -s)
+TORQUE_HOME=/var/spool/torque
+this_host=$(/bin/hostname -s)
 
-/usr/bin/logger -p local0.alert "********  running Compute prologue at $(date) for job PBS_JOBID $1"
+function check_status(){
+    # $1 = expected value
+    # $2 = status
+    # $3 = message if different
+    # Offline node if any checks fail and exit
 
-/usr/bin/logger -p local0.alert "running PBS error check at $(date)"
-
-# Temporarily disabling this while we deal wtih 
-# sisters not writing stderr and stdout files
-# /opt/torque/bin/pbsnodes $HOSTNAME | grep ERROR
-# if [ $? -eq 0 ] ; then
-#         /usr/bin/logger -p local0.alert  "prologue: pbs ERROR: prolog/epilog failed!  exit=6 "
-#         /opt/torque/bin/pbsnodes -N "ERROR: prolog/epilog failed!" $HOSTNAME
-#         /opt/torque/bin/pbsnodes -o $HOSTNAME
-# #        exit 6
-# fi
-
-/usr/bin/logger -p local0.alert "running hardware-check at $(date)"
-
-if [ -x /etc/rc.d/rocksconfig.d/post-98-hardware-check ] ; then
-  /etc/rc.d/rocksconfig.d/post-98-hardware-check
-  if [ $? -ne 0 ] ; then
-  /usr/bin/logger -p local0.alert "$HOSTNAME failed hardware-check at  $(date)"
-  exit 99
-  fi
-else      
-/usr/bin/logger -p local0.alert "post-98-hardware-check not found "  
-fi 
-
-# check for auotmount 
-     /bin/ps -ef |grep automount |grep -v grep > /dev/null 2>&1
-     st=$?
-     if [ $st -ne 0 ] ; then
-     /sbin/service autofs start >> /var/log/local0 2>&1
-     sleep 10
-     /bin/ps -ef |grep automount |grep -v grep > /dev/null 2>&1
-     st=$?
-       if [ $st -ne 0 ] ; then
-        /usr/bin/logger -p local0.alert  "prologue: automount not started, Giving up!  exit=2 "
-        /opt/torque/bin/pbsnodes -o $HOSTNAME
-        /opt/torque/bin/pbsnodes -N "automount failed" $HOSTNAME
-       exit 2
-       fi
-     fi
-
-# Add user to access list
-/usr/bin/perl -pi -e "s/(EXCEPT.*):/\$1 $PBS_USER:/" /etc/security/access.conf
-
-# remove left over lock files
-for i in $(cd /tmp; ls PBS_TEMP* 2>/dev/null )  ; do
-  test=${i%%".g"*}
-  test=${test##*'P_'}
-## qstat: Unknown Job Id rc = 153
-  /opt/torque/bin/qstat $test >/dev/null 2>&1
-  st=$?
-  if [ $st -eq 153 ] ; then
-  /usr/bin/logger -p local0.alert "prologue: removing leftover lock file /tmp/$i"
-  /bin/rm /tmp/$i
-  else
-  /usr/bin/logger -p local0.alert "prologue: rc=$st job $test running with lock /tmp/$i "
-  fi
-done
-
-# create lock file per user and job
-su - $PBS_USER -c "/bin/touch /tmp/PBS_TEMP_$PBS_JOBID "
-
-#Create Oasis scratch directory per job and user 
-      if [ -d /oasis/scratch/$PBS_USER/$PBS_JOBID ] ; then
-       /usr/bin/logger -p local0.alert "prologue: /oasis/scratch/$PBS_USER/$PBS_JOBID exists"
-      else 
-       /bin/mkdir -p /oasis/scratch/$PBS_USER/$PBS_JOBID
-       /bin/chmod o+rx /oasis/scratch/$PBS_USER
-       /bin/chown -R $PBS_USER.$GROUP /oasis/scratch/$PBS_USER/$PBS_JOBID
-      fi
-
-# Removed until all noflash nodes return
-# #create local per job scratch space
-# # check for scratch filesystem
-# if [[ $HOSTNAME == gcn-18-* || $HOSTNAME == gcn-19-* ]] ; then
-#    FLASH=noflash
-#  else
-#    FLASH=flash
-#    scra=sdb
-# fi
-FLASH=flash
-    
-if [[ $FLASH == "flash" ]] ; then
-    SCRA=$(/bin/mount| /bin/grep "$scra"| awk '{print $1}')
-    if [[ "$SCRA" != "" ]] ; then
-        /bin/mkdir -p /scratch/$PBS_USER/$PBS_JOBID
-        /bin/chmod o+rx /scratch/$PBS_USER
-        /bin/chown -R $PBS_USER /scratch/$PBS_USER/$PBS_JOBID
-        /usr/bin/logger -p local0.alert " created $PBS_USER.$GROUP /scratch/$PBS_USER/$PBS_JOBID"
-
-        # Log current usage of /scratch
-        block_usage=$(/bin/df -B 1024 /scratch | grep scratch)
-        inode_usage=$(/bin/df -i /scratch | grep scratch)
-        /usr/bin/logger -p local0.alert "sdsc_stats job start $PBS_JOBID $PBS_USER local scratch block usage $block_usage"
-        /usr/bin/logger -p local0.alert "sdsc_stats job start $PBS_JOBID $PBS_USER local scratch inode usage $inode_usage"
-    else
-        /usr/bin/logger -p local0.alert "prologue: /scratch filesystem not mounted "
-        /opt/torque/bin/pbsnodes -N "/scratch filesystem not mounted "  $HOSTNAME
-        /opt/torque/bin/pbsnodes -o $HOSTNAME
+    if [[ $1 != $2 ]] ; then
+        note=$3
+        /opt/torque/bin/pbsnodes -oN "$note" $this_host
+        /usr/bin/logger -p local0.alert "Node offlined due to: $note"
+        exit -1
     fi
+}
+
+# Action 1 - Look for PBS ERROR
+
+/opt/torque/bin/pbsnodes $this_host | grep ERROR  >& /dev/null
+check_status 0 $? "ERROR in Torque status"
+
+# Action 3 - Create user-job lock file
+/bin/su - $PBS_USER -c "/bin/touch /tmp/PBS_TEMP_$PBS_JOBID"
+
+# Action 5 - Create local scratch directory
+/bin/mkdir -p /scratch/$PBS_USER/$PBS_JOBID
+check_status 0 $? "Cannot create local scratch"
+/bin/chmod o+rx /scratch/$PBS_USER
+/bin/chown -R $PBS_USER /scratch/$PBS_USER/$PBS_JOBID
+
+# Check for node file to see if we're the mother superior
+if [[ -e /var/spool/torque/aux/$PBS_JOBID ]] ; then
+    # Action 5.5 (Mother Superior) - Create Oasis scratch dir
+    /bin/mkdir -p /oasis/scratch/$PBS_USER/$PBS_JOBID
+    check_status 0 $? "Lustre issue, unable to create Oasis scratch dir"
+    /bin/chmod o+rx /oasis/scratch/$PBS_USER
+    /bin/chown -R $PBS_USER.$PBS_GROUP /oasis/scratch/$PBS_USER/$PBS_JOBID
 else
-       /usr/bin/logger -p local0.alert "noflash node, no check on /scratch filesystem "
-fi      
+    # Action 5.5 (Sisters) - Touch stderr/stdout files
+    touch $TORQUE_HOME/spool/$PBS_JOBID.OU
+    touch $TORQUE_HOME/spool/$PBS_JOBID.ER
+fi
 
+# Action 6 - Add user to access list
 
+/bin/sed -i "s/\(EXCEPT.*\):/\1 $PBS_USER:/" access.conf
 
 exit 0
-
-
